# Generated by Django 5.0.6 on 2024-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_category', models.CharField(max_length=50)),
                ('blog_content', models.CharField(max_length=5000)),
            ],
        ),
    ]
