# Generated by Django 5.0.6 on 2024-08-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='blog_content',
            field=models.TextField(max_length=5000),
        ),
    ]
