# Generated by Django 5.0.6 on 2024-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0002_createblog_slug_alter_createblog_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='blog_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
