# Generated by Django 5.0.6 on 2024-08-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0003_alter_createblog_blog_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblog',
            name='slug',
        ),
        migrations.AlterField(
            model_name='createblog',
            name='blog_content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='blog_title',
            field=models.CharField(max_length=50),
        ),
    ]
